### PR TITLE
Update Splice chunlok/update-oos to version 0.1.19-snapshot.20240829.6581.0.vb98a2324 (automatic PR)

### PR DESCRIPTION
**Pull request by canton-network-da**
This PR updates branch chunlok/update-oos of Splice from the latest changes as of version 0.1.19-snapshot.20240829.6581.0.vb98a2324, commit DACH-NY/canton-network-node@b98a23243

### CODE REVIEW

**Comment by moritzkiefer-da** [comment]
wrong target branch

**Comment by chunlokling-da** [comment]
yeah this was created automatically from the canton internal repo. I want to use `[splice-cci-update-1724920424](https://github.com/digital-asset/decentralized-canton-sync/tree/splice-cci-update-1724920424)` and merge it to release-line-0.1.19

**Comment by chunlokling-da** [comment]
will make another PR with the correct target branch

**Comment by chunlokling-da** [comment]
https://github.com/digital-asset/decentralized-canton-sync/pull/56

**Pull request closed without merging**
